name: CD

on:
  release:
    types: [created]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
            version: v1.56.0
          

      - name: Run tests
        run: go test ./...

      - name: Build binary
        run: go build -o go-app

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: go-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
